### ISSUE TITLE
Missing Icons after latest Webman Amplifier update

### ISSUE THREAD

**Issue by Nevario** [webmandesign/webman-amplifier#1]
Hello,

Not sure if this is the right place to post.

I just did a webman-amplifier plugin update and since that update have lost a few icons.

![fontellomissingicons](https://cloud.githubusercontent.com/assets/2949564/6311729/53dbcadc-b9bb-11e4-9835-eac309f1fb3c.png)

I've checked the fontello.css and fontello.dev.css files and it looks like the definitions are really missing.

For example `icon-ok-circled` is nowhere to be seen in either of the new CSS files.

Any tips to get these icons back? Awesome plugin though!

Tim

**Comment by webmandesign** [comment]
Hi,

Please note that I provide support via http://support.webmandesign.eu.

The issue you experience was caused with the updated icon pack introduced in plugin's version 1.1.3.

To fix this, all you need to do is resave the icons font settings in **Appearance > Icon Font** (just click "Save changes" button.

You were notified about this in the plugins update comment in WordPress admin when updating to 1.1.3 version. https://github.com/webmandesign/webman-amplifier/blob/master/README.TXT#L100

Regards,

Oliver

**Comment by webmandesign** [comment]
And, BTW, if you are using some of these icons, please update accordingly: https://github.com/webmandesign/webman-amplifier/blob/master/assets/font/fontello.dev.css#L12
